url: http://shreyanya.com
baseurl:

# Site settings
title: Shrey weds Anya
email: your-email@domain.com
description: "This is a website for the upcoming wedding of Shrey and Anya on 12-12-2016."

# Build settings
markdown: kramdown
permalink: pretty
