url: http://shreyanya.com
baseurl:

# Site settings
title: Shreyans weds Anya
email: contact@shreyanya.com
description: "This webpage documents the wedding of Shrey and Anya , that took place on 12-12-16 at Ujjain, India."

# Build settings
markdown: kramdown
permalink: pretty
