url: http://shreyanya.com
baseurl:

# Site settings
title: Shreyans weds Anya
email: contact@shreyanya.com
description: "This is a webpage with information on the upcoming wedding of Shreyans and Anna on 12-12-2016 in Ujjain, India"

# Build settings
markdown: kramdown
permalink: pretty
